version: '3.3'

services:

  db:
    image: postgres:10.4
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: eSub
      POSTGRES_USER: es_admin
      POSTGRES_DB: english_subtitled
